services:
  - type: web
    plan: free
    name: workflow-novel-handler
    runtime: node
    buildCommand: bun install
    startCommand: bun --bun ./index.ts
    envVars:
      - key: PORT
        value: 3001